[package]
name = "selene_engines"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
selene_kernel_contracts = { path = "../selene_kernel_contracts" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
