[package]
name = "selene_os"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
selene_kernel_contracts = { path = "../selene_kernel_contracts" }
selene_engines = { path = "../selene_engines" }
selene_storage = { path = "../selene_storage" }
